# Generated by Django 2.2.7 on 2019-11-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_containerrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='media_type',
            field=models.CharField(choices=[('application/vnd.docker.container.image.v1+json', 'application/vnd.docker.container.image.v1+json'), ('application/vnd.docker.image.rootfs.diff.tar.gzip', 'application/vnd.docker.image.rootfs.diff.tar.gzip'), ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip', 'application/vnd.docker.image.rootfs.foreign.diff.tar.gzip'), ('application/vnd.oci.image.config.v1+json', 'application/vnd.oci.image.config.v1+json'), ('application/vnd.oci.image.layer.v1.tar+gzip', 'application/vnd.oci.image.layer.v1.tar+gzip'), ('application/vnd.oci.image.layer.nondistributable.v1.tar+gzip', 'application/vnd.oci.image.layer.nondistributable.v1.tar+gzip')], max_length=80),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='media_type',
            field=models.CharField(choices=[('application/vnd.docker.distribution.manifest.v1+json', 'application/vnd.docker.distribution.manifest.v1+json'), ('application/vnd.docker.distribution.manifest.v2+json', 'application/vnd.docker.distribution.manifest.v2+json'), ('application/vnd.docker.distribution.manifest.list.v2+json', 'application/vnd.docker.distribution.manifest.list.v2+json'), ('application/vnd.oci.image.manifest.v1+json', 'application/vnd.oci.image.manifest.v1+json'), ('application/vnd.oci.image.index.v1+json', 'application/vnd.oci.image.index.v1+json')], max_length=60),
        ),
    ]
