# Generated by Django 2.2.13 on 2020-06-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_oci_mediatype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerremote',
            old_name='whitelist_tags',
            new_name='allowlist_tags',
        ),
    ]
