# Generated by Django 2.2.12 on 2020-06-25 08:23

from django.db import migrations, models
import django.db.models.deletion
import pulp_container.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_increase_remote_artifact_size_field'),
        ('container', '0004_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRedirectContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='container_contentredirectcontentguard', serialize=False, to='core.ContentGuard')),
                ('shared_secret', models.BinaryField(default=pulp_container.app.models._gen_secret, max_length=32)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard',),
        ),
    ]
