# Generated by Django 4.2.16 on 2025-01-14 20:23

import os

from django.db import migrations, models
import django.db.models.deletion


def _gen_secret():
    return os.urandom(32)


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRedirectContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='container_contentredirectcontentguard', serialize=False, to='core.contentguard')),
                ('shared_secret', models.BinaryField(default=_gen_secret, max_length=32)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard',),
        ),
    ]
