# Generated by Django 2.2.14 on 2020-07-17 12:25

from django.db import migrations


def remove_tag_artifacts(apps, schema_editor):
    Tag = apps.get_model('container', 'Tag')
    for tag in Tag.objects.all():
        tag._artifacts.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_containerpushrepository'),
    ]

    operations = [
        migrations.RunPython(remove_tag_artifacts)
    ]
