# Generated by Django 2.2.14 on 2020-08-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_repository_remote'),
        ('container', '0007_clear_tags_artifacts_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha1',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha224',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha256',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha384',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha512',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='size',
        ),
        migrations.AddField(
            model_name='upload',
            name='cumulative_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BlobTemporaryUpload',
            fields=[
                ('pulptemporaryfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PulpTemporaryFile')),
                ('offset', models.BigIntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_uploads', to='container.Upload')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.pulptemporaryfile',),
        ),
    ]
