# Generated by Django 2.2.14 on 2020-08-10 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0007_clear_tags_artifacts_refs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerremote',
            old_name='whitelist_tags',
            new_name='include_tags',
        ),
        migrations.AddField(
            model_name='containerremote',
            name='exclude_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None),
        ),
    ]
