# Generated by Django 2.2.17 on 2020-11-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_file_field_to_uploadchunk'),
        ('container', '0009_container_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='pulp_created',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='pulp_id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='pulp_last_updated',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha1',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha224',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha256',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha384',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sha512',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='size',
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Upload'),
            preserve_default=False,
        ),
    ]
