# Generated by Django 2.2.17 on 2020-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_remove_uploadchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerrepository',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('sync_containerrepository', 'Can start a sync task'), ('modify_content_containerrepository', 'Can modify content in a repository'), ('build_image_containerrepository', 'Can use the image builder in a repository')]},
        ),
    ]
