# Generated by Django 2.2.17 on 2021-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_add_pull_push_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdistribution',
            name='private',
            field=models.BooleanField(default=False, help_text='Restrict pull access to explicitly authorized users. Defaults to unrestricted pull access.'),
        ),
    ]
