# Generated by Django 2.2.17 on 2021-01-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0014_containerdistribution_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerpushrepository',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('modify_content_containerpushrepository', 'Can modify content in a push repository')]},
        ),
    ]
