# Generated by Django 2.2.17 on 2021-02-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0016_add_delete_versions_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containernamespace',
            options={'permissions': [('namespace_add_containerdistribution', 'Add any distribution to a namespace'), ('namespace_delete_containerdistribution', 'Delete any distribution from a namespace'), ('namespace_view_containerdistribution', 'View any distribution in a namespace'), ('namespace_pull_containerdistribution', 'Pull from any distribution in a namespace'), ('namespace_push_containerdistribution', 'Push to any distribution in a namespace'), ('namespace_change_containerdistribution', 'Change any distribution in a namespace'), ('namespace_view_containerpushrepository', 'View any push repository in a namespace'), ('namespace_modify_content_containerpushrepository', 'Modify content in any push repository in a namespace')]},
        ),
    ]
