# Generated by Django 2.2.17 on 2021-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0017_add_granular_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdistribution',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
