# Generated by Django 3.2.9 on 2022-01-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_contentredirectcontentguard'),
        ('container', '0021_data_move_redirect_content_guard_to_core'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentRedirectContentGuard',
        ),
    ]
