# Generated by Django 4.2.16 on 2025-01-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0021_data_move_redirect_content_guard_to_core'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentRedirectContentGuard',
        ),
    ]
