# Generated by Django 3.2.9 on 2021-11-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0022_delete_contentredirectcontentguard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestSignature',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='container_manifestsignature', serialize=False, to='core.content')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('digest', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('atomic', 'atomic')], max_length=255)),
                ('key_id', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.PositiveIntegerField()),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('data', models.BinaryField()),
                ('signed_manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_manifests', to='container.manifest')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('digest',)},
            },
            bases=('core.content',),
        ),
    ]
