# Generated by Django 3.2.11 on 2022-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0024_containerremote_sigstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestsignature',
            name='data',
            field=models.TextField(),
        ),
    ]
