# Generated by Django 3.2.9 on 2021-11-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0025_signature_stored_in_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.signingservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.signingservice',),
        ),
        migrations.AddField(
            model_name='containerpushrepository',
            name='manifest_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_containerpushrepository', to='container.manifestsigningservice'),
        ),
        migrations.AddField(
            model_name='containerrepository',
            name='manifest_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_containerrepository', to='container.manifestsigningservice'),
        ),
    ]
