# Generated by Django 3.2.13 on 2022-05-09 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0030_enforce_tagged_manifest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='containernamespace',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='containerremote',
            name='exclude_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='containerremote',
            name='include_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='containerremote',
            name='upstream_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='digest',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='media_type',
            field=models.TextField(choices=[('application/vnd.docker.distribution.manifest.v1+json', 'application/vnd.docker.distribution.manifest.v1+json'), ('application/vnd.docker.distribution.manifest.v2+json', 'application/vnd.docker.distribution.manifest.v2+json'), ('application/vnd.docker.distribution.manifest.list.v2+json', 'application/vnd.docker.distribution.manifest.list.v2+json'), ('application/vnd.oci.image.manifest.v1+json', 'application/vnd.oci.image.manifest.v1+json'), ('application/vnd.oci.image.index.v1+json', 'application/vnd.oci.image.index.v1+json')]),
        ),
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='architecture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='os',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='os_version',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='variant',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manifestsignature',
            name='creator',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manifestsignature',
            name='digest',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manifestsignature',
            name='key_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='manifestsignature',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='manifestsignature',
            name='type',
            field=models.TextField(choices=[('atomic', 'atomic')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
