# Generated by Django 3.2.18 on 2023-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0034_translate_signed_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpushrepository',
            name='pending_blobs',
            field=models.ManyToManyField(related_name='container_containerpushrepository', to='container.Blob'),
        ),
    ]
