# Generated by Django 4.2.1 on 2023-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0035_alter_blob_content_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerpushrepository",
            name="pending_blobs",
            field=models.ManyToManyField(to="container.blob"),
        ),
        migrations.AddField(
            model_name="containerpushrepository",
            name="pending_manifests",
            field=models.ManyToManyField(to="container.manifest"),
        ),
    ]
