# Generated by Django 4.2.7 on 2024-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0037_create_pull_through_cache_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manifest',
            constraint=models.CheckConstraint(check=models.Q(('media_type__in', ['application/vnd.docker.distribution.manifest.v1+json', 'application/vnd.docker.distribution.manifest.v2+json', 'application/vnd.docker.distribution.manifest.list.v2+json', 'application/vnd.oci.image.manifest.v1+json', 'application/vnd.oci.image.index.v1+json'])), name='valid_media_type_choice'),
        ),
        migrations.AddConstraint(
            model_name='manifestsignature',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['atomic'])), name='valid_type_choice'),
        ),
    ]
