# Generated by Django 4.2.10 on 2024-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0038_add_manifest_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
