# Generated by Django 4.2.10 on 2024-03-05 11:22

from django.db import migrations, models


def move_manifest_data(apps, schema_editor):
    """
    Move the data from the manifest's linked file to the new data field.
    """
    Manifest = apps.get_model("container", "Manifest")

    for manifest in Manifest.objects.all():
        artifact = manifest._artifacts.first()
        if not artifact:
            continue

        file = artifact.file 
        json_data_text = file.read()
        file.close()

        manifest.data = json_data_text
        manifest._artifacts.clear()
        manifest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0038_add_manifest_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(move_manifest_data),
    ]
