# Generated by Django 4.2.10 on 2024-04-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0038_add_manifest_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBlob',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('data', models.TextField()),
                ('created', models.DateTimeField()),
                ('author', models.TextField(blank=True, default='')),
                ('os', models.TextField()),
                ('architecture', models.TextField()),
                ('digest', models.TextField(db_index=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('digest',)},
            },
            bases=('core.content',),
        ),
        migrations.AddField(
            model_name='containerpushrepository',
            name='pending_config_blobs',
            field=models.ManyToManyField(to='container.configblob'),
        ),
        migrations.AddField(
            model_name='containerrepository',
            name='pending_config_blobs',
            field=models.ManyToManyField(to='container.configblob'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_config_blob', to='container.configblob'),
        ),
    ]
