# Generated by Django 4.2.10 on 2024-03-05 11:22
import json
import warnings

from django.db import migrations, models
from django.core.files.storage import default_storage

from pulp_container.constants import (
    MEDIA_TYPE,
)

def get_content_data(artifact):
    with default_storage.open(artifact.file.name, mode="rb") as file:
        raw_data = file.read()
    content_data = json.loads(raw_data)
    return content_data, raw_data

def migrate_manifest_data(apps, schema_editor):
    """
    Migrate the backing artifact manifest to the new 'data' field.
    Also, initialize the 'annotations' and 'labels' fields.

    'is_bootable' and 'is_flatpak' fields are not initialized since they require annotations and 
    labels to be initialized first.
    """
    Manifest = apps.get_model("container", "Manifest")
    to_update = []
    manifests = Manifest.objects.filter(
        contentartifact__artifact__isnull=False
    ).distinct().prefetch_related("_artifacts").select_related("config_blob")
    for manifest in manifests.iterator(chunk_size=1000):
        manifest_artifact = manifest._artifacts.get()
        manifest_data, raw_bytes_data = get_content_data(manifest_artifact)
        manifest.data = raw_bytes_data.decode("utf-8")
        if not manifest.annotations:
            init_annotations(manifest, manifest_data)
        if not manifest.labels:
            init_labels(manifest)

        to_update.append(manifest)
        if len(to_update) > 1000:
            Manifest.objects.bulk_update(to_update, ["data", "annotations", "labels"])
            to_update.clear()
    if to_update:
        Manifest.objects.bulk_update(to_update, ["data", "annotations", "labels"])

def init_annotations(manifest, manifest_data):
    # annotations are part of OCI only
    if manifest.media_type not in (MEDIA_TYPE.MANIFEST_OCI, MEDIA_TYPE.INDEX_OCI):
        return

    manifest.annotations = manifest_data.get("annotations", {})

def init_labels(manifest):
    if manifest.config_blob:
        try:
            config_artifact = manifest.config_blob._artifacts.get()
        except models.ObjectDoesNotExist:
            return
        config_data, _ = get_content_data(config_artifact)
        manifest.labels = config_data.get("config", {}).get("Labels") or {}

class Migration(migrations.Migration):

    dependencies = [
        ("container", "0038_add_manifest_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifest",
            name="data",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(
            migrate_manifest_data,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
