# Generated by Django 4.2.13 on 2024-06-28 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0039_manifest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerpullthroughremote',
            name='excludes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='containerpullthroughremote',
            name='includes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
    ]
