# Generated by Django 4.2.13 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0040_add_remote_repo_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdistribution',
            name='max_payload_size',
            field=models.IntegerField(null=True),
        ),
    ]
