# Generated by Django 4.2.16 on 2024-10-21 19:14

import json
from django.db import migrations, models

from pulp_container.constants import MEDIA_TYPE, MANIFEST_TYPE, MANIFEST_MEDIA_TYPES, COSIGN_MEDIA_TYPES, COSIGN_MEDIA_TYPES_MANIFEST_TYPE_MAPPING


def migrate_manifest_nature(apps, schema_editor):
    """
    Populate the `type` field, and also the `is_bootable` and `is_flatpak` fields even though they are deprecated.
    """
    Manifest = apps.get_model("container", "Manifest")
    to_update = []
    # First, update the manifests that are not manifest lists or index manifests.
    manifests = Manifest.objects.filter(data__isnull=False).exclude(media_type__in=[MEDIA_TYPE.MANIFEST_LIST, MEDIA_TYPE.INDEX_OCI])
    for manifest in manifests.iterator():
        setattr(manifest, "json_manifest", json.loads(manifest.data))
        if init_manifest_nature(manifest):
            to_update.append(manifest)
        if len(to_update) > 1000:
            Manifest.objects.bulk_update(to_update, ["type", "is_bootable", "is_flatpak"])
            to_update.clear()
    if to_update:
        Manifest.objects.bulk_update(to_update, ["type", "is_bootable", "is_flatpak"])
        to_update.clear()
    # Then, update the manifest lists and index manifests.
    manifest_lists = Manifest.objects.filter(
        data__isnull=False, media_type__in=[MEDIA_TYPE.MANIFEST_LIST, MEDIA_TYPE.INDEX_OCI]
    ).prefetch_related("listed_manifests")
    for manifest_list in manifest_lists.iterator(chunk_size=1000):
        setattr(manifest_list, "json_manifest", json.loads(manifest_list.data))
        if init_manifest_list_nature(manifest_list):
            to_update.append(manifest_list)
        if len(to_update) > 1000:
            Manifest.objects.bulk_update(to_update, ["type", "is_bootable", "is_flatpak"])
            to_update.clear()
    if to_update:
        Manifest.objects.bulk_update(to_update, ["type", "is_bootable", "is_flatpak"])
        to_update.clear()

def init_manifest_list_nature(manifest_list):
    updated_type = False
    if not manifest_list.type:
        manifest_list.type = MANIFEST_TYPE.INDEX
        updated_type = True

    for manifest in manifest_list.listed_manifests.all():
        # it suffices just to have a single manifest of a specific nature;
        # there is no case where the manifest is both bootable and flatpak-based
        if manifest.type == MANIFEST_TYPE.BOOTABLE:
            manifest_list.is_bootable = True
            return True
        elif manifest.type == MANIFEST_TYPE.FLATPAK:
            manifest_list.is_flatpak = True
            return True

    return updated_type

def init_manifest_nature(manifest):
    if is_bootable_image(manifest):
        # DEPRECATED: is_bootable is deprecated and will be removed in a future release.
        manifest.is_bootable = True
        manifest.type = MANIFEST_TYPE.BOOTABLE
        return True
    elif is_flatpak_image(manifest):
        # DEPRECATED: is_flatpak is deprecated and will be removed in a future release.
        manifest.is_flatpak = True
        manifest.type = MANIFEST_TYPE.FLATPAK
        return True
    elif is_helm_chart(manifest):
        manifest.type = MANIFEST_TYPE.HELM
        return True
    elif media_type := is_cosign(manifest):
        manifest.type = get_cosign_type(media_type)
        return True
    elif is_artifact(manifest):
        manifest.type = MANIFEST_TYPE.ARTIFACT
        return True
    elif is_manifest_image(manifest):
        manifest.type = MANIFEST_TYPE.IMAGE
        return True

    return False

def is_bootable_image(manifest):
    return (
        manifest.annotations.get("containers.bootc") == "1"
        or manifest.labels.get("containers.bootc") == "1"
    )

def is_flatpak_image(manifest):
    return True if manifest.labels.get("org.flatpak.ref") else False

def is_manifest_image(manifest):
    return manifest.media_type in MANIFEST_MEDIA_TYPES.IMAGE

def is_cosign(manifest):
    try:
        # layers is not a mandatory field
        layers = manifest.json_manifest["layers"]
    except KeyError:
        return False

    for layer in layers:
        if layer["mediaType"] in COSIGN_MEDIA_TYPES:
            return layer["mediaType"]
    return False

def get_cosign_type(media_type):
    if media_type in MEDIA_TYPE.COSIGN_SBOM:
        return MANIFEST_TYPE.COSIGN_SBOM
    return COSIGN_MEDIA_TYPES_MANIFEST_TYPE_MAPPING.get(media_type, MANIFEST_TYPE.UNKNOWN)

def is_helm_chart(manifest):
    try:
        return manifest.json_manifest["config"]["mediaType"] == MEDIA_TYPE.CONFIG_BLOB_HELM
    except KeyError:
        return False

def is_artifact(manifest):
    # artifact is valid only for OCI spec
    if manifest.media_type != MEDIA_TYPE.MANIFEST_OCI:
        return False

    if manifest.json_manifest.get("artifactType", None):
        return True

    manifest_config_media_type = manifest.json_manifest["config"]["mediaType"]
    return (
        manifest_config_media_type == MEDIA_TYPE.OCI_EMPTY_JSON
        or manifest_config_media_type not in vars(MEDIA_TYPE).values()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0041_add_pull_through_pull_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='type',
            field=models.CharField(null=True),
        ),
        migrations.RunPython(migrate_manifest_nature, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
