# Generated by Django 4.2.16 on 2024-11-21 20:59

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_openpgpdistribution_openpgpkeyring_openpgppublickey_and_more'),
        ('container', '0043_add_os_arch_image_size_manifest_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blob',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='containernamespace',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manifest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manifestsignature',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blob',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='containernamespace',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='manifestsignature',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='tag',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='blob',
            unique_together={('digest', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='containernamespace',
            unique_together={('name', 'pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='manifest',
            unique_together={('digest', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='manifestsignature',
            unique_together={('digest', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'tagged_manifest', '_pulp_domain')},
        ),
    ]
