# Generated by Django 4.2.16 on 2025-03-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0044_add_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="compressed_image_size",
            field=models.BigIntegerField(null=True),
        ),
    ]
