# Generated by Django 4.2.16 on 2025-03-06 22:37
import json
import warnings
from django.db import migrations, models
from django.core.files.storage import default_storage

from pulp_container.constants import MEDIA_TYPE

def get_content_data(artifact):
    with default_storage.open(artifact.file.name, mode="rb") as file:
        raw_data = file.read()
    content_data = json.loads(raw_data)
    return content_data, raw_data

def migrate_os_arch_image_size(apps, schema_editor):
    """
    Populate the os, architecture, and compressed_image_size fields for the manifests.

    This migration can only handle manifests within the default domain.
    """
    Manifest = apps.get_model("container", "Manifest")
    to_update = []
    manifests = Manifest.objects.filter(data__isnull=False, pulp_domain__name="default").select_related("config_blob")
    for manifest in manifests.iterator():
        if needs_os_arch_size_update(manifest):
            manifest.json_manifest = json.loads(manifest.data)
            init_architecture_and_os(manifest)
            init_compressed_image_size(manifest)
            to_update.append(manifest)

            if len(to_update) > 1000:
                Manifest.objects.bulk_update(to_update, ["os", "architecture", "compressed_image_size"])
                to_update.clear()
    if to_update:
        Manifest.objects.bulk_update(to_update, ["os", "architecture", "compressed_image_size"])

    if Manifest.objects.exclude(pulp_domain__name="default").exists():
        warnings.warn(
            "Run 'pulpcore-manager container-handle-image-data' to update the manifests' "
            "os, architecture, and compressed_image_size fields."
        )

def needs_os_arch_size_update(manifest):
    return manifest.media_type not in [MEDIA_TYPE.MANIFEST_LIST, MEDIA_TYPE.INDEX_OCI] and not (
        manifest.architecture or manifest.os or manifest.compressed_image_size
    )

def init_architecture_and_os(manifest):
    # schema1 has the architecture/os definition in the Manifest (not in the ConfigBlob)
    # and none of these fields are required
    if manifest.json_manifest.get("architecture", None) or manifest.json_manifest.get("os", None):
        manifest.architecture = manifest.json_manifest.get("architecture", None)
        manifest.os = manifest.json_manifest.get("os", None)
    elif manifest.config_blob:
        try:
            config_artifact = manifest.config_blob._artifacts.get()
        except models.ObjectDoesNotExist:
            return
        config_data, _ = get_content_data(config_artifact)
        manifest.architecture = config_data.get("architecture", None)
        manifest.os = config_data.get("os", None)

def init_compressed_image_size(manifest):
    # manifestv2 schema1 has only blobSum definition for each layer
    if manifest.json_manifest.get("fsLayers", None):
        manifest.compressed_image_size = 0
        return

    layers = manifest.json_manifest.get("layers")
    compressed_size = 0
    for layer in layers:
        compressed_size += layer.get("size")
    manifest.compressed_image_size = compressed_size

class Migration(migrations.Migration):

    dependencies = [
        ("container", "0044_add_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="compressed_image_size",
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(
            migrate_os_arch_image_size,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
