# Generated by Django 5.2.6 on 2025-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0045_alter_manifest_compressed_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='listed_manifests',
            field=models.ManyToManyField(through='container.ManifestListManifest', through_fields=('image_manifest', 'manifest_list'), to='container.manifest'),
        ),
    ]
