# Generated by Django 5.2.6 on 2026-01-27 00:00

from django.contrib.postgres.fields import HStoreField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0046_alter_manifest_listed_manifests'),
    ]

    operations = [
        migrations.AddField(
            model_name='containernamespace',
            name='pulp_labels',
            field=HStoreField(default=dict),
        ),
    ]
