# Generated by Django 5.2.11 on 2026-04-15 02:37

import base64
import logging

from django.db import migrations, models

from pysequoia.packet import PacketPile, Tag


logger = logging.getLogger(__name__)


def keyid_from_fingerprint(fingerprint):
    if len(fingerprint) == 40:
        return fingerprint[-16:]
    elif len(fingerprint) == 64:
        return fingerprint[:16]
    else:
        raise ValueError(f"Unexpected fingerprint length: {len(fingerprint)}")


def populate_fingerprint(apps, schema_editor):
    ManifestSignature = apps.get_model("container", "ManifestSignature")

    batch = []
    for sig in ManifestSignature.objects.filter(fingerprint__isnull=True).iterator():
        try:
            signature_raw = base64.b64decode(sig.data)
            pile = PacketPile.from_bytes(signature_raw)
        except Exception as exc:
            logger.warning("Could not parse signature %s, skipping fingerprint extraction", sig.pk)
            logger.warning(str(exc))
            continue

        fingerprint = None
        for packet in pile:
            if packet.tag == Tag.Signature:
                if packet.issuer_fingerprint is not None:
                    fingerprint = packet.issuer_fingerprint.upper()
                    break
                elif packet.issuer_key_id is not None:
                    # No fingerprint available, only key_id — nothing new to store
                    break

        if fingerprint:
            assert sig.key_id == keyid_from_fingerprint(fingerprint), (
                f"Signature {sig.pk}: key_id {sig.key_id} does not match "
                f"fingerprint {fingerprint}"
            )
            sig.fingerprint = fingerprint
            batch.append(sig)

        if len(batch) > 500:
            ManifestSignature.objects.bulk_update(batch, ["fingerprint"])
            batch.clear()

    if batch:
        ManifestSignature.objects.bulk_update(batch, ["fingerprint"])

class Migration(migrations.Migration):

    dependencies = [
        ('container', '0048_containerremote_includes_excludes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsignature',
            name='fingerprint',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.RunPython(
            populate_fingerprint,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
