# Generated by Django 5.2 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0050_alter_containernamespace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerremote',
            name='auto_discover_cosign',
            field=models.BooleanField(default=True),
        ),
    ]
